### ISSUE TITLE
Extract more field and meta data?

### ISSUE THREAD

**Issue by de-code** [allenai/science-parse#109]
Hi,

Are there any plans to extract more fields in the foreseeable future?

For example:

* the body text could include more markup
* there is an _affiliations_ field that seems to be always empty (but is also not documented as a field)
* references may include more properties
* coordinates to the location in the source document would help to reconcile it with other extraction tools

Another related question, do you have a bit more information on the scope of the_venue_ field? It looks like it could be a conference name or a journal for example. Perhaps anything that doesn't fit into the other reference fields (_title_, _author_, _year_)?

Thank you

**Comment by de-code** [comment]
Thank you for the great answer.

Yes, it seems like deep learning models are having the edge and I can see similar plans elsewhere as well. Is your new model already available? Is that using _allennlp_? Do you have plans for a wider scope of extraction fields for that model?

What training data do you use?

**Comment by dirkgr** [comment]
The new model is not available yet, but it's actually really close. I'm basically just waiting for approval to make it public. To be sure though, the new system also doesn't have any additional fields. It's just title, author, and bibliographies. Since science-parse also provides sections and abstract, we are currently using both systems side-by-side.

It is not using allennlp. Unfortunately allennlp was not ready when I started development on SPv2. If I were to re-do it now, I would probably use it.

We used the open-access papers from PubMed Central. There are a few more details in this paper, section 3: https://arxiv.org/abs/1805.02262
